apiVersion: hub.0xhub.io/v1
kind: Project
metadata:
  name: example-web-app
  namespace: default
spec:
  name: Example Web Application
  description: A sample web application demonstrating the Project CRD
  url: https://example.com
  icon: https://example.com/icon.png
  category: web
  status: active

